name: Build ArmCpuInfo

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: install deps
      run: sudo apt-get install git gcc-aarch64-linux-gnu build-essential uuid-dev iasl git  nasm  python-is-python3
      
    - name: checkout EDK2
      run: git clone --depth 1 https://github.com/tianocore/edk2.git

    - name: checkout EDK2 submodules
      run: git submodule update --init
      working-directory: edk2
      
    - name: checkout ArmCpuInfo
      uses: actions/checkout@v4
      with:
        path: edk2/ArmPkg/Application/ArmCpuInfo
  
    - name: enable ArmCpuInfo
      run: echo "ArmPkg/Application/ArmCpuInfo/ArmCpuInfo.inf" >> edk2/ArmPkg/ArmPkg.dsc 

    - name: build BaseTools
      run: make -C edk2/BaseTools
      env:
        WORKSPACE: $PWD
        GCC_AARCH64_PREFIX: aarch64-linux-gnu-
        PACKAGES_PATH: $WORKSPACE/edk2
      
    - name: build
      run: source edk2/edksetup.sh; build -t GCC -a AARCH64 -b RELEASE -m edk2/ArmPkg/Application/ArmCpuInfo/ArmCpuInfo.inf -p edk2/ArmPkg/ArmPkg.dsc
